### ISSUE TITLE
Occasional exception

### ISSUE THREAD

**Issue by ogrady** [FlussuferOrga/ts-gw2-verifyBot#19]
Exceptions occurs regularily during reauth
```
Jun 15 21:53:47 .stratoserver.net python3.6[2577]: ts3.query.TS3QueryError: error id 512: invalid clientID
Jun 15 21:53:47 .stratoserver.net python3.6[2577]: Traceback (most recent call last):
Jun 15 21:53:47 .stratoserver.net python3.6[2577]:   File "/home/ts3bot/ts-gw2-verifyBot/TS3Bot.py", line 147, in ts3exec
Jun 15 21:53:47 .stratoserver.net python3.6[2577]:     res = handler(self.ts_connection)
Jun 15 21:53:47 .stratoserver.net python3.6[2577]:   File "/home/ts3bot/ts-gw2-verifyBot/TS3Bot.py", line 236, in <lambda>
Jun 15 21:53:47 .stratoserver.net python3.6[2577]:     if any(perm_grp.get('name') == self.verified_group for perm_grp in self.ts_connection.ts3exec(lambda ts_connection: ts_connection.query("servergroupsbyclientid", cldbid = client_db_id).all())[0]):
Jun 15 21:53:47 .stratoserver.net python3.6[2577]:   File "/home/ts3bot/.local/lib/python3.6/site-packages/ts3/query_builder.py", line 219, in all
Jun 15 21:53:47 .stratoserver.net python3.6[2577]:     resp = self.fetch()
Jun 15 21:53:47 .stratoserver.net python3.6[2577]:   File "/home/ts3bot/.local/lib/python3.6/site-packages/ts3/query_builder.py", line 196, in fetch
Jun 15 21:53:47 .stratoserver.net python3.6[2577]:     return self._ts3conn.exec_query(self)
Jun 15 21:53:47 .stratoserver.net python3.6[2577]:   File "/home/ts3bot/.local/lib/python3.6/site-packages/ts3/query.py", line 755, in exec_query
Jun 15 21:53:47 .stratoserver.net python3.6[2577]:     return self._wait_for_resp(timeout=timeout)
Jun 15 21:53:47 .stratoserver.net python3.6[2577]:   File "/home/ts3bot/.local/lib/python3.6/site-packages/ts3/query.py", line 621, in _wait_for_resp
Jun 15 21:53:47 .stratoserver.net python3.6[2577]:     raise TS3QueryError(resp)
```

**Comment by Xyaren** [comment]
The error is typical when the Teamspak Server is queried with a (to it) **unknown** client id.

**Comment by Xyaren** [comment]
Is this still an issue?
