### ISSUE TITLE
Error when assigning guild roles

### ISSUE THREAD

**Issue by ogrady** [FlussuferOrga/ts-gw2-verifyBot#2]
```
BOT Event: Something went wrong during message received from teamspeak server. Likely bad user command/message.
 error id 1540: convert error
 Traceback (most recent call last):
   File "/home/ts3bot/ts-gw2-verifyBot/TS3Bot.py", line 419, in message_event_handler
     self.updateGuildTags(rec_from_uid, auth)
   File "/home/ts3bot/ts-gw2-verifyBot/TS3Bot.py", line 226, in updateGuildTags
     uid = self.getTsUniqueID(client_db_id)
   File "/home/ts3bot/ts-gw2-verifyBot/TS3Bot.py", line 309, in getTsUniqueID
     return self.ts_connection.query("clientgetnamefromdbid", cldbid=client_db_id).first().get('cluid')
   File "/home/ts3bot/.local/lib/python3.6/site-packages/ts3/query_builder.py", line 208, in first
     resp = self.fetch()
   File "/home/ts3bot/.local/lib/python3.6/site-packages/ts3/query_builder.py", line 196, in fetch
     return self._ts3conn.exec_query(self)
   File "/home/ts3bot/.local/lib/python3.6/site-packages/ts3/query.py", line 759, in exec_query
     return self._wait_for_resp(timeout=timeout)
   File "/home/ts3bot/.local/lib/python3.6/site-packages/ts3/query.py", line 625, in _wait_for_resp
     raise TS3QueryError(resp)
 ts3.query.TS3QueryError: error id 1540: convert error
```

**Comment by Xyaren** [comment]
Is this still an Issue ?
This might be fixed already.

**Comment by Xyaren** [comment]
Did not happen again.
