### ISSUE TITLE
Route for getting commanders always returns an empty result

### ISSUE THREAD

**Issue by ogrady** [FlussuferOrga/ts-gw2-verifyBot#33]
Only related output in the logs is
```
Jul 22 10:25:57 .stratoserver.net python3.6[5521]: 2020-07-22 10:25:57,329 [DEBUG] ts3.query: Sending query: 'channelgroupclientlist cgid=9'.
Jul 22 10:25:57 .stratoserver.net python3.6[5521]: 2020-07-22 10:25:57,342 [DEBUG] ts3.query: Sending query: 'clientgetnamefromdbid cldbid=6'.
```

Output is always:
```
{"commanders":[]}
```

although at least one user has the appropriate role.

**Comment by ogrady** [comment]
Update: the above behaviour only occurs when the user is not verified (that should warrant a warning, at least...).
Repeating the test with a registered user yields:
```
Jul 22 10:33:10 .stratoserver.net python3.6[5521]: 2020-07-22 10:33:10,795 [DEBUG] bot.ts.ThreadSafeTSConnection: Exception caught in default_exception_handler:
Jul 22 10:33:10 .stratoserver.net python3.6[5521]: Traceback (most recent call last):
Jul 22 10:33:10 .stratoserver.net python3.6[5521]:   File "/home/ts3bot/ts-gw2-verifyBot/bot/ts/ThreadSafeTSConnection.py", line 123, in ts3exec
Jul 22 10:33:10 .stratoserver.net python3.6[5521]:     res = handler(self.ts_connection)
Jul 22 10:33:10 .stratoserver.net python3.6[5521]:   File "/home/ts3bot/ts-gw2-verifyBot/bot/command_checker.py", line 52, in <lambda>
Jul 22 10:33:10 .stratoserver.net python3.6[5521]:     lambda t, cluid=db_entry["ts_db_id"]: t.query("clientgetnamefromuid", cluid).first().get("name"))  # no, there is probably no easier way to do this. I checked.
Jul 22 10:33:10 .stratoserver.net python3.6[5521]:   File "/home/ts3bot/.local/lib/python3.6/site-packages/ts3/query_builder.py", line 208, in first
Jul 22 10:33:10 .stratoserver.net python3.6[5521]:     resp = self.fetch()
Jul 22 10:33:10 .stratoserver.net python3.6[5521]:   File "/home/ts3bot/.local/lib/python3.6/site-packages/ts3/query_builder.py", line 196, in fetch
Jul 22 10:33:10 .stratoserver.net python3.6[5521]:     return self._ts3conn.exec_query(self)
Jul 22 10:33:10 .stratoserver.net python3.6[5521]:   File "/home/ts3bot/.local/lib/python3.6/site-packages/ts3/query.py", line 755, in exec_query
Jul 22 10:33:10 .stratoserver.net python3.6[5521]:     return self._wait_for_resp(timeout=timeout)
Jul 22 10:33:10 .stratoserver.net python3.6[5521]:   File "/home/ts3bot/.local/lib/python3.6/site-packages/ts3/query.py", line 621, in _wait_for_resp
Jul 22 10:33:10 .stratoserver.net python3.6[5521]:     raise TS3QueryError(resp)
Jul 22 10:33:10 .stratoserver.net python3.6[5521]: ts3.query.TS3QueryError: error id 1539: parameter not found
```
